### ISSUE TITLE
Ability to generate taxonomies and custom taxonomies

### ISSUE THREAD

**Issue by stuartcusackie** [alanpilloud/wp-faker#9]
It would be useful for me to be able to generate taxonomies. There may be a way to do this already but I can't think of an easy way off the top of my head.

Thanks for making this package!

**Comment by alanpilloud** [comment]
Hello Stuart,

Thanks for your kind comment, and sorry for this late response.

I decided to indicate that this package is unmaintained as it is the case : https://github.com/alanpilloud/wp-faker/blob/master/README.md

For your use case, if I understand correctly, I would first register the taxonomy with a mu-plugin.

Then, to populate the taxonomy, you could use WP-CLI. For instance : 

```
list='a b c d';
for element in $list;do 
    wp term create category $element;
done;
```

Which will create terms a b c and d in the category taxonomy.

See https://developer.wordpress.org/cli/commands/term/create/

Or if you dont need to specify the list of terms, you could use this : 
https://developer.wordpress.org/cli/commands/term/generate/

I hope it helped.

**Comment by stuartcusackie** [comment]
Thank you Alan, this is very helpful, and thanks for your work on this.
